### ISSUE TITLE
NameError: name 'QgsProject' is not defined

### ISSUE THREAD

**Issue by AlisterH** [CaptainDang/save_all#2]
```
2023-09-15T00:39:16     WARNING    Traceback (most recent call last):
              File "C:\Users/alister/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SaveAllScript\save_all.py", line 194, in run
             NameError: name 'QgsProject' is not defined
```
I need to add this in save_all.py to make it work:
`from qgis.core import QgsProject`

**Comment by AlisterH** [comment]
Actually, trying to actually go through with a save, there are a number of other similar errors, which prompted me to make that `from qgis.core import *`
But then I end up at this:
```
Traceback (most recent call last):
  File "C:\Users/alister/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SaveAllScript\save_all.py", line 328, in run
    error, error_string = QgsVectorFileWriter.writeAsVectorFormat(layer, output_file,
TypeError: QgsVectorFileWriter.writeAsVectorFormat(): arguments did not match any overloaded call:
  overload 1: argument 'symbologyExport' has unexpected type 'bool'
  overload 2: argument 4 has unexpected type 'QgsCoordinateReferenceSystem'
  overload 3: argument 3 has unexpected type 'str'
```

**Comment by AlisterH** [comment]
If I remove most of the layers in my project first I don't get that last error; I'll have to investigate further next week.

**Comment by CaptainDang** [comment]
Hi, I have some clarifying questions because I need some more details to better understand the problem you are having. From my knowledge, "from Qgis.core import *" should import all libraries from qgis.core, including QgsProject. Which version of QGIS are you using? Also, what types of layers are you trying to save? Are they vector or raster layers because the current version of the script does not work perfectly with layers that aren't either vector or raster.

**Comment by AlisterH** [comment]
> From my knowledge, "from Qgis.core import *" should import all libraries from qgis.core, including QgsProject.

Yes, that's why I added it.  I see you have also added it - but after the latest release.

> Which version of QGIS are you using?

Both 3.32.1 and a nightly that is a few weeks old.

> Also, what types of layers are you trying to save? 

For one project I'm testing with I have isolated the problem to several shape files - it isn't obvious to me why these files are problematic, but I have attached one of them:
[test_attachments.zip](https://github.com/CaptainDang/save_all/files/12643711/test_attachments.zip)

> Are they vector or raster layers because the current version of the script does not work perfectly with layers that aren't either vector or raster.

If other types of layers cause similar errors it might be good to look at handling them more gracefully.

**Comment by AlisterH** [comment]
Also, it seems that sometimes the original project file is overwritten.  I thought this was occurring when there was that error with the layers, but it doesn't seem to reliably happen, so I'm not sure now, but I guess it is something to keep an eye out for.

**Comment by AlisterH** [comment]
> > Also, what types of layers are you trying to save?
> 
> For one project I'm testing with I have isolated the problem to several shape files - it isn't obvious to me why these files are problematic, but I have attached one of them: [test_attachments.zip](https://github.com/CaptainDang/save_all/files/12643711/test_attachments.zip)

Actually, perhaps all shape files generate the error - I thought I had a whole lot more shapefile layers in these projects, but most of them were actually gpkg, and all the shapefile layers seem to error.

**Comment by CaptainDang** [comment]
Sorry it took me so long to get back. When I originally wrote this script, the intended audience was for some fellow co-workers. I don't believe we worked with any files like the once you put in that attachment, which is why the script can't handle them -- why, I have no idea as of right now. If I have some time down the road, I will try and address the problems.
