### ISSUE TITLE
this error

### ISSUE THREAD

**Issue by w4ri0** [CaptainDang/save_all#5]
2023-10-20T14:48:20     WARNING    Traceback (most recent call last):
              File "C:\Users/Gabriel_Dagon/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\autoSaver\autosave.py", line 370, in cronEvent
              self.saveCurrentProject()
              File "C:\Users/Gabriel_Dagon/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\autoSaver\autosave.py", line 417, in saveCurrentProject
              os.rename(bakFileName, targetBakFile)
             OSError: [WinError 123] La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte: 'geopackage://C:/Users/Gabriel_Dagon/Desktop/abu-dhabi_uoa_uob_final/skuu/skuuu_bak.gpkg?projectName=skuuuu' -> 'geopackage://C:/Users/Gabriel_Dagon/Desktop/abu-dhabi_uoa_uob_final/skuu/skuuu.gpkg?projectName=skuuuu.bak'
             
2023-10-20T15:03:20     WARNING    Traceback (most recent call last):
              File "C:\Users/Gabriel_Dagon/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\autoSaver\autosave.py", line 370, in cronEvent
              self.saveCurrentProject()
              File "C:\Users/Gabriel_Dagon/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\autoSaver\autosave.py", line 417, in saveCurrentProject
              os.rename(bakFileName, targetBakFile)
             OSError: [WinError 123] La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte: 'geopackage://C:/Users/Gabriel_Dagon/Desktop/abu-dhabi_uoa_uob_final/skuu/skuuu_bak.gpkg?projectName=skuuuu' -> 'geopackage://C:/Users/Gabriel_Dagon/Desktop/abu-dhabi_uoa_uob_final/skuu/skuuu.gpkg?projectName=skuuuu.bak'

**Comment by CaptainDang** [comment]
I am not quite sure of the problem, but I would guess that it is because you have a "?" in your filename? Operating systems do not like it when you use special characters, such as "?" in filenames.
